[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "networkx>=3.4.2",
    "numpy>=2.2.0",
    "rust-just>=1.38.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
